### ISSUE TITLE
Chat UI won't open

### ISSUE THREAD

**Issue by auradata** [NVIDIA/workbench-example-local-rag#4]
Hi, the chat app fails to open with no error message, when I run the start command '!/opt/conda/envs/ui-env/bin/python3 -m chatui' from in terminal in JupyterLab I get the following error:

```
Traceback (most recent call last):
  File "/opt/conda/envs/ui-env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/ui-env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/project/code/chatui/__main__.py", line 100, in <module>
    from chatui import api, chat_client, configuration, pages
  File "/project/code/chatui/api.py", line 4, in <module>
    import gradio as gr
  File "/opt/conda/envs/ui-env/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/opt/conda/envs/ui-env/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/opt/conda/envs/ui-env/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
ImportError: cannot import name 'set_documentation_group' from 'gradio_client.documentation' (/opt/conda/envs/ui-env/lib/python3.10/site-packages/gradio_client/documentation.py)
```

**Comment by RockyMtnBri** [comment]
Same here.

**Comment by auradata** [comment]
Fixed with latest version

**Comment by RockyMtnBri** [comment]
Chat is still not working. It opens, but when you enter text into it, you get no result.
